Kevinhanna/pan 329 fix assert issue
whereby/browser-sdk pull request #81
Opened 2023-10-12 21:43 UTC by kevinwhereby

see original PR that I accidentally merged here: https://github.com/whereby/browser-sdk/pull/79
and the revert here: https://github.com/whereby/browser-sdk/pull/80
🤦 

### Description

We are having some funny module resolution problems with rollup, so this pr aims to replace it with esbuild

Adds build steps for individual react/embed builds as well

### Gotchas
Esbuild can't emit typescript declarations, so we have to do it with `tsc`
Unfortunately, [tsc can't generate es6 concatenated declarations](https://github.com/microsoft/TypeScript/issues/2568) so we include the full directory structure... is this a problem? 

### To Test
- `yarn` to install the stuff
- `yarn build` to generate the builds and types
-  import it into a demo project

### Screenshots
Here's me importing just the react bundle like `import { useRoomConnection } from "@whereby.com/browser-sdk/react"`
![image](https://github.com/whereby/browser-sdk/assets/138459303/de84f069-795d-4d11-a617-157aa75d9892)

and using the embed bundle in a script tag like
`<script type="module" src="./node_modules/@whereby.com/browser-sdk/dist/embed/index.esm.js"></script>`
![image](https://github.com/whereby/browser-sdk/assets/138459303/fd574173-a757-463d-a854-41112af6e97a)

2023-10-12 21:43 UTC, kevinwhereby commented
@havardholvik oops sorry

2023-10-13 09:57 UTC, kevinwhereby commented
@havardholvik re. the /react and /embed imports, what do you think about moving that to a different PR considering everything else seems to be working here?

2023-10-13 09:59 UTC, havardholvik commented
> @havardholvik re. the /react and /embed imports, what do you think about moving that to a different PR considering everything else seems to be working here?

Im fine with that, as long as we see an improvement (and no regressions) with what we have today 👍

2023-10-13 10:46 UTC, kevinwhereby commented
Ah I lied, CRA still doesn't work..

2023-10-13 16:31 UTC, kevinwhereby commented
OK this _finally_ works on CRA and Vite as an import and a script tag referencing the bundled `embed.esm.js` file (unless I'm mistaken)

2023-10-16 06:52 UTC, havardholvik requested changes
If this PR aims at solving the assert-related issue we are seeing; I'm still getting the `process is not defined` error when trying out this build in Vite
<img width="714" alt="Screenshot 2023-10-16 at 08 50 37" src="https://github.com/whereby/browser-sdk/assets/778534/194dce3b-850b-445d-acbb-4284d640c8fa">

2023-10-16 07:58 UTC, kevinwhereby commented
@havardholvik wanna compare configs?
vite 4.4.5
react 18.2
typescript 5.02
```javascript
// vite.config.js
export default defineConfig({
    plugins: [react()],
    define: {
        "process.env": {},
    },
    build: {
        minify: false,
    },
    server: {
        port: 6006,
    },
});
```

```javascript
//tsconfig
{
    "compilerOptions": {
        "target": "es2016",
        "useDefineForClassFields": true,
        "lib": ["esnext", "DOM", "DOM.Iterable"],
        "module": "esnext",
        "skipLibCheck": true,

        /* Bundler mode */
        "moduleResolution": "bundler",
        "allowImportingTsExtensions": true,
        "resolveJsonModule": true,
        "isolatedModules": true,
        "noEmit": true,
        "jsx": "react-jsx",

        /* Linting */
        "strict": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noFallthroughCasesInSwitch": true
    },
    "include": ["src"],
    "references": [{ "path": "./tsconfig.node.json" }]
}
```

2023-10-16 10:54 UTC, havardholvik approved these changes
Vite works for me now once the process.env is defined 👍  Make sure also that we support our own environment variables, I think @nandito have been using them to eg override signal and api host.

2023-10-16 10:55 UTC, havardholvik commented on build.js
> +    target: ["es2016"],
I know this was my recommendation, but seeing we target es6 in our tsconfig, I think we should use that here as well

2023-10-17 09:51 UTC, merged